server:
    port: 8100
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css,application/font-woff2
spring:
    application:
        name:  restapi3
